on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  codecept-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo principal
      - name: Checkout main code
        uses: actions/checkout@v3

      # Paso 2: Checkout del historial de Allure (gh-pages)
      - name: Checkout Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-history

      # Pasos de instalaci贸n...
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.1'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      # Ejecuci贸n de pruebas
      - name: Run tests
        run: npx codeceptjs run --features --plugins allure

      # Generaci贸n del reporte Allure
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages-history
          allure_results: allure-results
          allure_history: allure-history

      # Despliegue a GitHub Pages
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history