name: Ejecutar pruebas CodeceptJS

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecept-test:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repo
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.1'

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores de Playwright
        run: npx playwright install chromium

      - name: Ejecutar pruebas
        run: npx codeceptjs run --features

      - name: Generar reporte HTML de Allure
        run: npm run allure:generate

      - name: Subir resultados raw de Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: output/allure-results/

      - name: Subir reporte HTML de Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: output/allure-report/

        - name: Publicar reporte HTML de Allure
          uses: simple-elf/allure-report-action@v1
          with:
            report-path: output/allure-report/
            auto-open: true
